baseurl = "http://durtchrt.github.io/blog/"
title = "개발 저장소"
theme = "hugo_theme_robust"
languageCode = "en-us"
copyright = "durtchrt"
googleAnalytics = "UA-86354121-1"
disqusShortname = "bjm"

[Taxonomies]
    tag = "tags"

[Params]
  Author = "durtchrt"
    
